name: Builds and tests entire application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  python_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ./api/requirements.txt;
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov

  react_build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node version 18.16.1
      uses: actions/setup-node@v4
      with:
        node-version: "18.16.1"
    - name: Install dependencies
      run: |
        cd client
        npm ci
        npm run build --if-present
    - name: Test with Vitest
      run: |
        npx vitest --coverage.enabled;
